name: Build for Hostinger

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create API config from GitHub Secrets (optional)
        run: |
          mkdir -p public/api
          cat > public/api/config.local.php << 'PHP'
          <?php
          // Generado por GitHub Actions en tiempo de build. No se versiona.
          // Si no defines estos secretos en el repo, este archivo puede quedar con valores vacíos.
          define('DB_HOST', '${{ secrets.DB_HOST }}');
          define('DB_PORT', '${{ secrets.DB_PORT }}');
          define('DB_NAME', '${{ secrets.DB_NAME }}');
          define('DB_USER', '${{ secrets.DB_USER }}');
          define('DB_PASS', '${{ secrets.DB_PASS }}');
          define('MAIL_TO', '${{ secrets.MAIL_TO }}');
          if ('${{ secrets.ALLOW_ORIGIN }}' !== '') define('ALLOW_ORIGIN', '${{ secrets.ALLOW_ORIGIN }}');
          if ('${{ secrets.SMTP_HOST }}' !== '') define('SMTP_HOST', '${{ secrets.SMTP_HOST }}');
          if ('${{ secrets.SMTP_USER }}' !== '') define('SMTP_USER', '${{ secrets.SMTP_USER }}');
          if ('${{ secrets.SMTP_PASS }}' !== '') define('SMTP_PASS', '${{ secrets.SMTP_PASS }}');
          if ('${{ secrets.SMTP_SECURE }}' !== '') define('SMTP_SECURE', '${{ secrets.SMTP_SECURE }}');
          if ('${{ secrets.SMTP_PORT }}' !== '') define('SMTP_PORT', (int) '${{ secrets.SMTP_PORT }}');
          if ('${{ secrets.SMTP_FROM }}' !== '') define('SMTP_FROM', '${{ secrets.SMTP_FROM }}');
          if ('${{ secrets.SMTP_FROM_NAME }}' !== '') define('SMTP_FROM_NAME', '${{ secrets.SMTP_FROM_NAME }}');
          PHP

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish dist to hostinger-build branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: hostinger-build
          folder: dist
          clean: true
